# Generated by Django 3.0.5 on 2020-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('full_address', models.TextField()),
                ('contact_1', models.CharField(max_length=13, null=True)),
                ('contact_2', models.CharField(max_length=13, null=True)),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
    ]
