# Generated by Django 3.0.5 on 2020-05-01 22:04

from django.db import migrations


def create_data(apps, schema_editor):
    ngos = apps.get_model('backend', 'NGO')
    ngos(ngo_id="KA/2018/0193297",
    name="AABHARI TRUST",
    city="Bengaluru",
    state="KARNATAKA",
    address_line="No.61, Bhavani Nagar, DB Kallu Channanayakana Palya, Nagasandra Post Bengaluru560073",
    contact_1="9986782712",
    contact_2="").save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
