# Generated by Django 3.0.5 on 2020-05-13 15:00

from django.db import migrations
import os
import pandas as pd

def create_data(apps, schema_editor):
    print('pass')

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
