# Generated by Django 3.0.5 on 2020-05-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_NGO'),
    ]

    operations = [
    ]
